//
//  CookViewModel.swift
//  Cooker
//
//  Created by Yongye Tan on 2/17/24.
//

import Foundation

@Observable class CookViewModel {
    
    var selectedPreferences: [String] = []
    var selectedCuisines: [String] = []
    
    var selectedRecipe: [Recipe] = []
    
    var allRecipes: [Recipe] = []
    
    
    init() {
        allRecipes = [
            Recipe(id: 1, imageName: "cheesepizza", recipeName: "cheesepizza", cookTime: 30, cuisine: "USA", dietaryPreferences: ["Vegan"], ingredients: ["apple"], instructions: ["cook", "clean", "eat"], description: "Cheese Pizza is a classic dish featuring a thin crust or dough topped with tomato sauce, melted cheese, and often various optional toppings, baked to perfection for a simple and universally loved comfort food."),
            Recipe(id: 2, imageName: "food", recipeName: "1", cookTime: 30, cuisine: "USA", dietaryPreferences: ["no milk"], ingredients: ["apple"], instructions: ["cook", "clean", "eat"], funFact: "A dialog is a type of modal window that appears in front of app content to provide critical information, or prompt for a decision to be made.", description: "testing food"),
            Recipe(id: 3, imageName: "p2", recipeName: "Butternut squash with red lentils and tamarind", cookTime: 25, cuisine: "Indian", dietaryPreferences: ["Vegetarian", "Vegan"], ingredients: ["1 butternut squash, peeled and cut into 1-inch dice", "1 tsp. nigella seeds (kalonji)", "½ tsp. dried red chile flakes", "½ tsp. salt", "1 Tbsp. sunflower oil", "1 Tbsp. mustard oil", "1 tsp. fenugreek seeds", "2 onions, finely chopped", "200g (about 1 cup) masoor dal (red lentils)", "1 tsp. ground coriander", "½ tsp. chile powder", "5 cups plus 1 Tbsp. boiling water", "1 Tbsp. tamarind paste", "1 Tbsp. grated jaggery or brown sugar", "2 Tbsp. coconut cream", "Handful fresh cilantro leaves, to garnish (optional)"], instructions: ["First, roast the squash. Preheat the oven to 350°F. Spread out the diced squash on a baking tray and sprinkle over the nigella seeds, chile flakes and salt. Drizzle with the oil and mix well. Roast for 40 minutes, until soft and lightly browned.",  "Meanwhile, start making the dal. Heat the mustard oil in a large saucepan over medium–low heat until it begins to smoke. Add the fenugreek and nigella seeds and let them sizzle for 1–2 minutes, then add the onions and cook for 10 minutes, until softened.",  "Tip in the lentils, salt, ground coriander and chile powder and mix well. Pour in the measured boiling water and bring to the boil. Cover the pan with a lid and cook over medium–low heat for 15 minutes or until the lentils are cooked.", "Stir the tamarind paste and jaggery into the saucepan, then carefully mix in the roasted butternut squash. Reduce the heat to low, cover the pan with a lid and simmer for 10 minutes, until the dal has thickened.", "Add the coconut cream and mix well. Take the pan off the heat and sprinkle over the cilantro leaves, if using them. Serve immediately."], description: "Roasting the butternut squash before it’s added gives this masoor dal sweet, concentrated flavor to balance the tangy tamarind."),
            Recipe(id: 4, imageName: "p3", recipeName: "Sunflower Saag With Black-Eyed Peas", cookTime: 20, cuisine: "Indian", dietaryPreferences: ["Vegan", "Vegetarian"], ingredients: ["2 tsp. neutral oil, such as sunflower", "1 Tbsp. coriander seeds", "1½ tsp. cumin seeds", "1 yellow onion, diced (about 2 cups)", "½ tsp. salt", "6 garlic cloves, minced or crushed (about 1½ Tbsp.)", "1 Tbsp. minced ginger", "1 green chile, minced", "⅓ cup hulled, roasted sunflower seeds (or use raw for a smoother sauce)", "½ tsp. ground turmeric", "4 cups packed, roughly chopped kale (about 5 ounces)", "2 tsp. neutral oil", "1 cup corn", "One 15.5-ounce can black-eyed peas, drained and rinsed", "1 Tbsp. nutritional yeast, optional", "1 tsp. garam masala", "Juice of ½ lime (about 2 tsp.), or to taste", "Freshly chopped cilantro, optional", "Sunflower seeds, for garnish"], instructions: ["Heat the oil in a wide pan or braising pan over medium heat. Add the coriander and cumin seeds, and continue to heat until fragrant, about 1 minute.",  "Add the onion and salt, and stir occasionally, until the onion is softened and starting to brown, 10 minutes. Adjust the heat between medium-low and medium to prevent the onions from browning too quickly.",  "Reduce the heat to low, add the garlic, ginger, and chile, and stir until fragrant, 2 minutes. Stir in the sunflower seeds and turmeric, and add 1 cup water.", "Increase the heat to medium and bring to a simmer. Add the kale, stir, cover, and continue to cook until the kale has wilted, 2 to 3 minutes. Remove from the heat and transfer to a bowl or blender, let cool for a few minutes, then blend until mostly smooth. Set aside.", "Heat the oil over medium heat in the pan. Sauté the corn until it starts to soften, about 3 minutes.", "Add the black-eyed peas, gravy, nutritional yeast (if using), and garam masala, and simmer until well combined, 3 to 5 minutes. Add ¼ to ½ cup (60 to 120 ml) water as needed to reach the desired consistency.", "Remove from the heat, adjust the salt to taste, squeeze on the lime juice, and garnish with cilantro and sunflower seeds, if desired."], description: "This creamy and hearty saag gets its texture from sunflower seed cream, which mellows the bitter notes of the kale."),
            Recipe(id: 5, imageName: "p4", recipeName: "Shoyu Butter Udon Noodle", cookTime: 12, cuisine: "Japanese", dietaryPreferences: ["Vegan", "Vegetarian"], ingredients: ["14 oz (400 g) pre-cooked udon noodles", "2 Tbsp (28 g) unsalted vegan butter", "7.1 oz (200 g) shiitake mushrooms, sliced", "2 stalks green onion, sliced", "1 Tbsp (15 mL) dark soy sauce", "1½ Tbsp (22 mL) mushroom stir-fry sauce, plus more to taste", "½ tsp garlic powder", "¾ cup (105 g) frozen shelled edamame"], instructions: ["Fill a saucepan with boiling water, and add the udon noodles. Cook for 2 minutes, then drain.", "Meanwhile, add the butter and mushrooms to a large pan on high heat. Cook until the mushrooms are lightly golden, about 4 minutes.", "Add the drained noodles, green onion, soy sauce, mushroom sauce, and garlic powder. Cook for 1 minute.", "Lastly, add the edamame beans and cook until heated through. Enjoy!"], description: "Thick chewy noodles are combined with shiitake mushrooms and edamame beans coated in a buttery, umami sauce. This recipe comes together more quickly than take-out and is just as delicious! It's the perfect meal for busy weeknights."),
            
            Recipe(id: 6, imageName: "p1", recipeName: "Chow Mein", cookTime: 20, cuisine: "Chinese", dietaryPreferences: ["Vegan", "Vegetarian", "Kosher"], ingredients: ["3 Tbsp (45 mL) dark soy sauce, plus more to taste", "2 Tbsp (30 mL) water", "2 Tbsp (30 mL) toasted sesame oil", "½ vegetable bouillon cube, crumbled", "2 tsp (5 g) cornstarch", "2 tsp (10 mL) agave syrup", "1 tsp (5 mL) sriracha hot sauce", "1 tsp (5 mL) rice vinegar", "½ Tbsp (7 mL) vegetable oil", "1 cup (168 g) mock chicken pieces, torn into shreds", "1 Tbsp (15 mL) vegetable oil", "1 medium onion, thinly sliced", "2 cloves garlic, minced", "5.3 oz (150 g) vegan chow mein noodles", "¼ napa cabbage, thinly sliced", "2 carrots, julienned", "1 head of bok choy, thinly sliced, stems and leaves separated", "toasted sesame seeds", "sliced green onion", "crispy chili oil"], instructions: ["Combine sauce ingredients in a jar or small bowl.", "Add the oil to sauté pan on high heat. Cook the mock chicken pieces until golden. Transfer to a plate and set aside.", "Add the some more oil to the now-empty pan. Cook the onion and garlic in the pan until the garlic becomes golden.", "Then add the cabbage, carrots, and white stems of the bok choy. Cook for 3 - 4 minutes.", "Meanwhile, cook the noodles according to the package directions. Then drain and rinse with cold water to stop the cooking process.", "Add the mock chicken back to the pan along with the bok choy leaves. Cook until warmed through.", "Stir through the cooked noodles, then pour over the sauce and toss to combine. Cook for 3 minutes to allow the cornstarch to thicken.", "Serve with green onions and sesame seeds. Enjoy!"], description: "To effortlessly serve up this dish that outshines takeout, the secret is having all your vegetables chopped and prepped. Once you begin cooking, this recipe comes together swiftly, and with everything ready, the entire meal flows seamlessly.")
        
        ]
    }
}
